name:                aoc2021
version:             1.0.0.0
github:              "StephenSwat/aoc2021-hs"
license:             Unlicense
author:              "Stephen Nicholas Swatman"
maintainer:          "stephen@v25.nl"

dependencies:
  - base >= 4.7 && < 5
  - split
  - extra
  - containers
  - multiset
  - bifunctors
  - regex-pcre
  - mtl
  - pqueue
  - sbv

executables:
  aoc2021:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
      - -Wall
      - -Wcompat
      - -O3
